vahay/urls.py
from django.conf.urls import url, include
from vahay import views

app_name = 'vahay'

urlpatterns = [
    url(r'^vahay-details/(?P<pk>\d+)/$', views.vahay_details, name='vahay_details'),
    url(r'^vahay-details/(?P<pk>\d+)/edit-vahay/$', views.edit_vahay, name='edit_vahay'),
    url(r'^add-vahay/$', views.add_vahay, name='add_vahay'),
    url(r'^(?P<pk>\d+)/edit-vahay/$', views.edit_vahay, name='edit_vahay'),
	url(r'^delete-vahay/(?P<pk>\d+)/$', views.delete_vahay, name='delete_vahay'),
	url(r'^residents/delete-resident/(?P<pk>\d+)/$', views.delete_resident, name='delete_resident'),
	url(r'^residents/profile/(?P<pk>\d+)/$', views.resident_profile, name='resident_profile'),
	url(r'^reservations/(?P<pk>\d+)/$', views.reservations, name='reservations'),
	url(r'^reservations/(?P<pk>\d+)/confirm/$', views.confirm_reservation, name='confirm_reservation'),	

	# url(r'^delete-vahay/(?P<pk>\d+)/$', views.delete_vahay, name='delete_vahay
	# url(r'^approve/(?P<pk>\d+)/$', views.approve_reservation, name='approve_reservation'),
	url(r'^deny-reserve/(?P<pk>\d+)/$', views.deny_reservation, name='deny_reservation'),
	url(r'^vahay-list/$', views.get_list_vahay, name='vahay_list'),
	url(r'^vahay-list/(?P<pk>\d+)/$', views.m_get_vahay, name='m_get_vahay'),
	# TO TEST
	url(ur'^reserve/(?P<email>.*)/(?P<vahayId>.*)/$', views.reserve_vahay, name='reserve_vahay'),
	url(r'^cancel-reserve/$', views.cancel_reservation, name='cancel_reservation'),
	url(r'^balance/(?P<email>.*)/$', views.get_balance, name='get_balance'),

	url(r'^pay/(?P<email>.*)/$', views.pay_rental, name='pay_rental'),
]

vhayad/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.home, name='home'),
    url(r'^sign-out$', views.sign_out, name='sign_out'),
    
    url(r'^payment/', include('payment.urls')),
    url(r'^vahay/', include('vahay.urls')),
]

vahay/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import get_object_or_404
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Vahay(models.Model):
	owner = models.ForeignKey(User, on_delete=models.CASCADE)
	name = models.CharField(max_length=255)
	rent = models.IntegerField(default=0)
	category = models.CharField(max_length=100)
	contact_details = models.CharField(max_length=100)
	vote = models.IntegerField(default=0)
	available = models.BooleanField(default=1)
	description = models.CharField(max_length=500)
	address = models.CharField(max_length=500)
	email = models.CharField(max_length=500,default="example@email.com")
	account_num = models.IntegerField(default=0)

	def __str__(self):
		return self.name + " - " + self.owner.username

	def isAvailable(self):
		if self.available == 1:
			return True
		else:
			return False

	def getOwner(self):
		return self.owner.last_name + ", " + self.owner.first_name

	def main_as_json(self):
		return {
			"id" : self.id,
			"name"	: self.name,
			"address": self.address,
			"vote" : self.vote
			}

	def details_as_json(self):
		return {
			"id" : self.id,
			"owner" : self.owner.first_name + " " + self.owner.last_name,
			"name" : self.name,
			"rent": self.rent,
			"category" : self.category,
			"contact_details" : self.contact_details,
			"available" : self.available,
			"description" : self.description,
			"email" : self.email, 	
			"address" : self.address,
			"vote" : self.vote
			}

	def account_as_json(self):
		return {
			"account_num" : self.account_num,
		}	


class Image(models.Model):
	vahay = models.ForeignKey(Vahay, on_delete=models.CASCADE)
	link = models.CharField(max_length=1000)

	def __str__(self):
		return self.vahay.name + " - " + self.link


class Transaction(models.Model):
	sender = models.IntegerField(default=0)
	trans_type = models.CharField(max_length=15)
	recipient = models.IntegerField(default=0)
	remarks = models.CharField(max_length=100, blank=True)
	time = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return str(self.id)

	def as_json(self):
		return {
			"resident" : get_object_or_404(Resident, pk=self.sender),
			"vahay" : get_object_or_404(Vahay, pk=self.recipient)
		}


class Resident(models.Model):
	name = models.CharField(max_length=100)
	age = models.IntegerField(default=0)
	occupation = models.CharField(max_length=100)
	home_address = models.CharField(max_length=100)
	email = models.CharField(max_length=100)
	account_num = models.IntegerField(default=0)
	vahay = models.ForeignKey(Vahay, on_delete=models.CASCADE, null=True, blank=True)
	user = models.ForeignKey(User, on_delete=models.CASCADE)

	def __str__(self):
		return self.name;

	def account_as_json(self):
		return {
			"id" : self.id,
			"account_num" : self.account_num,
			"vahay": self.vahay
		}	


class Payment(models.Model):
	vahay = models.ForeignKey(Vahay, on_delete=models.CASCADE)
	resident = models.ForeignKey(Resident, on_delete=models.CASCADE)
	amount = models.IntegerField(default=0)


class Reservation(models.Model):
	sender = models.ForeignKey(Resident, on_delete=models.CASCADE)
	recipient = models.ForeignKey(Vahay, on_delete=models.CASCADE)
	remarks = models.CharField(max_length=100, blank=True)
	time = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return str(self.id)

vahay/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from .models import Vahay, Resident, Transaction
from .models import Image, Payment, Reservation
from django.core import serializers


import payment
import json

# Create your views here.

def vahay_details(request, pk):
	if not request.user.is_authenticated:
		return redirect('/')

	vahay = get_object_or_404(Vahay, pk=pk)
	images = Image.objects.filter(vahay=vahay)
	residents = Resident.objects.filter(vahay=vahay)
	context = {
		'vahay': vahay,
		'images': images,
		'residents': residents
	}
	return render(request, 'vahay/vahayDetails.html', context=context)


def add_vahay(request):
	if not request.user.is_authenticated:
		return redirect('/')

	if request.method == 'POST':
		name = request.POST.get('name')
		category = request.POST.get('category')
		contact_details = request.POST.get('contact_details')
		rent= request.POST.get('rent')
		address = request.POST.get('address')
		description = request.POST.get('description')
		email = request.POST.get('email')
		accountnum = request.POST.get('accountnum')
		Vahay.objects.create(owner=request.user, name=name, category=category, contact_details=contact_details, 
			rent=rent, vote=1, available=True, description=description, address=address, email=email,
			account_num=accountnum)
		return redirect('/')

	return render(request, 'vahay/addVahay.html')


def edit_vahay(request, pk):
	if not request.user.is_authenticated:
		return redirect('/')

	vahay = get_object_or_404(Vahay, pk=pk)
	context = {
		'vahay': vahay
	}

	if request.method == "POST":
		vahay.name = request.POST.get('vahay_name')
		vahay.rent = request.POST.get('rent')
		vahay.category = request.POST.get('category')
		vahay.contact_details = request.POST.get('contacts')
		vahay.address = request.POST.get('address')
		vahay.description = request.POST.get('description')
		vahay.email = request.POST.get('email')
		vahay.account_num = request.POST.get('accountnum')
		if request.POST.get('available', None) == None:
			vahay.available = 0
		else:
			vahay.available = 1

		vahay.save()
		if request.POST['image_link']:
			image_link = request.POST.get('image_link')
			Image.objects.create(vahay=vahay, link=image_link)
		return redirect('/')

	return render(request, 'vahay/editVahay.html', context=context)


def delete_vahay(request, pk):
	vahay = get_object_or_404(Vahay, pk=pk)
	vahay.delete()

	return redirect('/')


def delete_resident(request, pk):
	resident = get_object_or_404(Resident, pk=pk)
	resident.delete()

	return redirect('/')


def resident_profile(request, pk):
	resident = get_object_or_404(Resident, pk=pk)
	payment = get_object_or_404(Payment, resident=resident)
	print resident.name
	context = {
		'resident': resident,
		'payment': payment
	}

	return render(request, 'vahay/residentProfile.html', context=context)
	

def reservations(request, pk):
	if not request.user.is_authenticated:
		return redirect('/')

	vahay = get_object_or_404(Vahay, pk=pk)
	transactions = Reservation.objects.filter(recipient=vahay)
	context = {
		'transactions': transactions,
		'vahay' : vahay
	}

	return render(request, 'vahay/reservations.html', context=context)


def confirm_reservation(request, pk):
	if not request.user.is_authenticated:
		return redirect('/')

	transaction = get_object_or_404(Reservation, pk=pk)
	vahay = transaction.recipient
	sender = transaction.sender
	sender.vahay = vahay
	sender.save()

	transaction.delete()
	Payment.objects.create(vahay=vahay,resident=sender, amount=vahay.rent)

	images = Image.objects.filter(vahay=vahay)
	residents = Resident.objects.filter(vahay=vahay)
	context = {
		'vahay': vahay,
		'images': images,
		'residents': residents
	}

	return render(request, 'vahay/vahayDetails.html', context=context)


def approve_reservation(request, pk):

	if not request.user.is_authenticated:
		return redirect('/')

	transaction = get_object_or_404(Transaction, pk=pk)
	if request.method == 'POST':
		transaction.trans_type = 'approved'
		transaction.save()
		response = payment.bank.pay(transaction.recipient,transaction.sender)

		resident = get_object_or_404(Vahay, pk=transaction.sender)
		resident.vahay = transaction.recipient
		resident.save()

	return redirect('/')

def deny_reservation(request, pk):

	if not request.user.is_authenticated:
		return redirect('/')

	transaction = get_object_or_404(Transaction, pk=pk)
	if request.method == 'POST':
		transaction.trans_type = 'denied'
		transaction.save()

	return redirect('/')


#MOBILE
def get_list_vahay(request):

	# list_vahay = serializers.serialize('json', Vahay.objects.all())
	list_obj = Vahay.objects.all()
	# vahays = [obj.as_json() for obj in list_obj]
	
	print "GET list_vahay"
	# return HttpResponse(list_vahay, content_type="application/json")
	list_vahay = [ obj.main_as_json() for obj in list_obj ]
	return HttpResponse(json.dumps({"houses": list_vahay}), content_type='application/json')


def m_get_vahay(request, pk):

	# list_vahay = serializers.serialize('json', Vahay.objects.all())
	list_obj = Vahay.objects.filter(pk=pk)
	# vahays = [obj.as_json() for obj in list_obj]
	
	print "GET vahay"
	# return HttpResponse(list_vahay, content_type="application/json")
	vahay = [ obj.details_as_json() for obj in list_obj ]
	return HttpResponse(json.dumps({"houses": vahay}), content_type='application/json')


def reserve_vahay(request, email, vahayId):

	sender_name = email
	print sender_name

	result = Resident.objects.filter(email=sender_name)
	sender = [ obj.account_as_json() for obj in result ]
	sender_id = sender[0]['id']

	resident = get_object_or_404(Resident, pk=sender_id)

	recipient = get_object_or_404(Vahay, pk=vahayId)
	# result1 = vahay.models.Vahay.objects.filter(owner=recipient)
	# recipient = [ obj.account_as_json() for obj in result ]
	# recipient_id = recipient[0]['account_num']

	remarks = ''

	print "POST reservation"
	new_transaction = Reservation.objects.create(sender=resident,recipient=recipient,remarks=remarks)
	return HttpResponse(json.dumps({'success':'yehey'}), content_type='application/json')


def pay_rental(request, email):
	print "POST payment"
	sender_name = email

	result = Resident.objects.filter(email=sender_name)
	sender = [ obj.account_as_json() for obj in result ]
	sender_id = sender[0]['id']

	vahay = sender[0]['vahay']
	recipient = vahay.id
	trans_type = 'payment'
	remarks = ''
	print "POST payment"
	new_transaction = Transaction.objects.create(sender=sender_id,recipient=recipient,trans_type=trans_type,remarks=remarks)
	trans_id = new_transaction.id

	print "POST payment"
	response = payment.bank.pay(sender_id,recipient,vahay.rent,trans_id)


	resident = get_object_or_404(Resident, pk=sender_id)
	payments = get_object_or_404(Payment, resident=resident)

	amount_to_pay = payments.amount
	payments.amount = 0
	payments.save();
	print payments.amount
	return HttpResponse(json.dumps({'success':'yehey', 'balance': amount_to_pay}), content_type='application/json')


def cancel_reservation(request, pk):

	transaction = get_object_or_404(Transaction, pk=pk)
	if request.method == 'POST':
		transaction.trans_type = 'cancelled'
		transaction.save()
		print "GET cancel reservation"
		return HttpResponse(json.dumps({'success':'cancelled'}), content_type='application/json')


def get_balance(request, email):

	result = Resident.objects.filter(email=email)
	resident = [ obj.account_as_json() for obj in result ]
	resident_id = resident[0]['id']

	payment = get_object_or_404(Payment, pk=resident_id)
	balance = payment.amount

	return HttpResponse(json.dumps({'balance': balance}), content_type='application/json')

vahay/templates/vahay/addVahay.html
{% extends 'base.html' %}
{% block title %}Create Vahay{% endblock %}

{% block body %}

	<div class="panel panel-default col-sm-4 col-md-4 col-lg-4 col-lg-offset-4 add_vahay">
	  	<div class="panel-body ">
			<h4 style="text-align: center;">Create vahay</h4>
				<form class="form-horizontal" action="{% url 'vahay:add_vahay'%}" method="POST">
					{% csrf_token %}
					<div class="form-group">
						<input type="text" name="name" class="form-control" placeholder="Name" required>
				   </div>
				   <div class="form-group">
						<input type="text" name="category" class="form-control" placeholder="Category" required>
				   </div>
				   <div class="form-group">
						<input type="number" name="rent" class="form-control" placeholder="rent" required>
				   </div>
				  	<div class="form-group">
						<input type="text" name="contact_details" class="form-control" placeholder="Contact" required>
				   </div>
				   <div class="form-group">
						<input type="text" name="address" class="form-control" placeholder="Complete Adress" required>
				   </div>
				   <div class="form-group">
						<input type="text" name="description" class="form-control" placeholder="Other Details" required>
				   </div>
				   <div class="form-group">
						<input type="text" name="email" class="form-control" placeholder="email" required>
				   </div>
				   <div class="form-group">
						<input type="number" name="accountnum" class="form-control" placeholder="account number" required>
				   </div>
					<div class="form-group">
						<button type="submit" class="btn btn-success col-lg-offset-6"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span>&nbsp;Create</button>
						<a href="{% url 'home' %}" class="btn btn-danger"><span class="glyphicon glyphicon-remove"></span>&nbsp;Cancel</a>
					</div>
				</form>
	  	</div>
	</div>

{% endblock %}

vahay/templates/vahay/editVahay.html
{% extends 'base.html' %}
{% block title %}Vahay-Edit{% endblock %}

{% block body %}
	<div class="panel panel-default col-sm-4 col-md-4 col-lg-4 col-lg-offset-4 edit_vahay">
	  	<div class="panel-body ">
			<h4 style="text-align: center;">Edit vahay</h4>
			<form class="form-horizontal" action="{% url 'vahay:edit_vahay' vahay.pk %}" method="POST">
				{% csrf_token %}
				<div class="form-group">
					<input type="text" name="vahay_name" class="form-control" placeholder="Name" value="{{ vahay.name }}" required>
				</div>
				<div class="form-group">
					<input type="text" name="category" class="form-control" placeholder="Category" value="{{ vahay.category }}" required>
				</div>
				<div class="form-group">
					<input type="text" name="contacts" class="form-control" placeholder="Contact Details" value="{{ vahay.contact_details }}" required>
				</div>
				<div class="form-group">
					<input type="text" name="address" class="form-control" placeholder="Address" value="{{ vahay.address }}" required>
				</div>
				</div><div class="form-group">
					<input type="number" name="rent" class="form-control" placeholder="Rent" value="{{ vahay.rent }}" required>
				</div>
				<div class="form-group">
					<input type="text" name="email" class="form-control" placeholder="Email" value="{{ vahay.email }}" required>
				</div><div class="form-group">
					<input type="number" name="accountnum" class="form-control" placeholder="Account Number" value="{{ vahay.account_num }}" required>
				</div>
				<div class="form-group">
					<input type="text" name="description" class="form-control" placeholder="Description" value="{{ vahay.description }}" required>
				</div>
				{% if vahay.isAvailable %}
				   <div class="form-group">
					    <input type="checkbox" name="available" checked>&nbsp;&nbsp;Available
				   </div>
			   {% else %}
				   <div class="form-group">
					   <input type="checkbox" name="available">&nbsp;&nbsp;Available
				   </div>
			   {% endif %}<br>
			   <label for="basic-url">Add Image</label>
		   	<div class="form-group">
					<div class="input-group">
						<span class="input-group-addon" id="basic-addon3">Link</span>
						<input type="text" name="image_link" class="form-control" id="basic-url" aria-describedby="basic-addon3">
					</div>
				</div>
				<div class="form-group">
					<button type="submit" class="btn btn-success col-lg-offset-7"><span class="glyphicon glyphicon-save" aria-hidden="true"></span>&nbsp;Save</button>
					<a href="{% url 'vahay:vahay_details' vahay.pk %}" class="btn btn-danger">Cancel</a>
				</div>
			</form>
	  	</div>
	</div>
	

{% endblock %}

vahay/templates/vahay/reservations.html
{% extends 'base.html' %}
{% block title %}Reservations{% endblock %}

{% block body %}
	<section class="Reservations" style="margin-top: 50px;">
	  <div class="panel panel-default col-lg-6 col-lg-offset-3">
		<h3 style="text-align:center;">Reservations</h3>
			<div class="panel-body">
				<div class="container-fluid">
					{% for transaction in transactions %}
						<div class="well col-lg-12">
							<p>Name: <strong>{{ transaction.sender.name }}</strong></p>
							<div class="row">
								<div class="col-lg-6">
									<p>Date: {{ transaction.time }}</p>
								</div>
								<div class="col-md-2 col-md-offset-3">
									<a href="{% url 'vahay:confirm_reservation' transaction.pk %}" class="btn btn-success">Confirm</a>
								</div>
							</div>
							<p>Email: {{ transaction.sender.email }}</p>
						</div>
					{% endfor %}
				</div>
			</div>
		</div>

{% endblock %}

vahay/templates/vahay/residentProfile.html
{% extends 'base.html' %}
{% block title %}{{ resident.name }}{% endblock %}

{% block body %}
	<section class="resident" style="margin-top:50px;">
	  <div class="panel panel-default col-lg-6 col-lg-offset-3">
		<h3 style="text-align:center;">Resident's Profile</h3>
			<div class="panel-body">
				<div class="container-fluid">
					<div class="well col-lg-12">
						<p><strong>Name:</strong> {{ resident.name }}</p>
						<p><strong>Age:</strong> {{ resident.age }}</p>
						<p><strong>Occupation:</strong> {{ resident.occupation }}</p>
						<p><strong>Home Address:</strong> {{ resident.home_address }}</p>
						<p><strong>Email:</strong> {{ resident.email }}</p>
						<p><strong>Amount to pay:</strong> Php {{ payment.amount }}.00</p>
					</div>
				</div>
			</div>
		<a href="{% url 'vahay:vahay_details' resident.vahay.pk %}" class="btn btn-success col-lg-offset-5" style="margin-bottom: 15px;"><span class="glyphicon glyphicon-chevron-left"></span>Go back</a>
		</div>
	</section>
	

{% endblock %}

vahay/templates/vahay/vahayDetails.html
{% extends 'base.html' %}
{% block title %}Vahay-{{ vahay.name }}{% endblock %}

{% block body %}

	<section class="gallery">
		<section class="vahay_title">
	  		<h3>{{ vahay.name.upper }}</h3>
		</section>
		{% if images.count <= 0 %}
		<p style="text-align: center;">No images to show</p>
		{% else %}
			<div id="vahay_carousel" class="carousel slide col-lg-6 col-lg-offset-3" data-ride="carousel">
				<div id="vahay_carousel-inner" class="carousel-inner" role="listbox">
				  <div class="item active">
						<img src="{{ images.0.link }}" alt="image">
				  </div>
				  {% for image in images %}
						<div class="item">
							 <img src="{{ image.link }}" alt="image">
						</div>
				  {% endfor %}
				</div>
				<a class="left carousel-control" href="#vahay_carousel" role="button" data-slide="prev">
				  <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
				  <span class="sr-only">Previous</span>
				</a>
				<a class="right carousel-control" href="#vahay_carousel" role="button" data-slide="next">
				  <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
				  <span class="sr-only">Next</span>
				</a>
			</div>
		{% endif %}
	</section>

	 <section class="info">
		  <div class="panel panel-default col-lg-6 col-lg-offset-3">
				<div class="panel-body">
				<div class="container-fluid">
					<div class="row">
						<div class="col-md-6">
							<p><span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>&nbsp;<strong>Favorites:</strong> <span class="badge">{{ vahay.vote }}</span></p>
						</div>
						<div class="col-md-3 col-md-offset-3">
							<p><span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>&nbsp;{{ reviews.count }} <strong>review/s</strong></p>
						</div>
					</div>
					<div class="row">
						<div class="col-md-6">
							<p><span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp;<strong>Owner:</strong> {{ vahay.getOwner }}</p>
						</div>
						<div class="col-md-3 col-md-offset-3">
  							{% if vahay.isAvailable %}
							  <p style="color:green;"><strong>Now Available</strong>&nbsp;<span class="glyphicon glyphicon-ok-sign" aria-hidden="true"></span></p>
							{% else %}
							  <p style="color:red;"><strong>Not Available</strong>&nbsp;<span class="glyphicon glyphicon-remove-sign" aria-hidden="true"></span></p>
							{% endif %}
  						</div>
					</div>
					<div class="row">
						<div class="col-md-6">
							<p><span class="glyphicon glyphicon-home" aria-hidden="true"></span>&nbsp;<strong>Category:</strong> {{ vahay.category.upper }}</p>
						</div>
					</div>
					<div class="row">
						<div class="col-md-6">
							<p><span class="glyphicon glyphicon-usd" aria-hidden="true"></span>&nbsp;<strong>Rent:</strong> Php {{ vahay.rent }}.00</p>
						</div>
						<div class="col-md-2 col-md-offset-3">
							{% if vahay.owner == user %}
							  <a href="{% url 'vahay:edit_vahay' vahay.pk %}" class="btn btn-xs btn-primary">Edit Vahay</a>
							{% else %}
							  <form action="#" method="POST">
									{% csrf_token %}
									<button class="btn btn-sm btn-primary"><strong>Favorite</strong>&nbsp;<span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span></button>
							  </form>
							{% endif %}
						</div>
					</div>
					<div class="row">
						<div class="col-md-6">
							<p><span class="glyphicon glyphicon-earphone" aria-hidden="true"></span>&nbsp;<strong>Contact details:</strong> {{ vahay.contact_details }}</p>
						</div>
						<div class="col-md-2 col-md-offset-3">
							{% if vahay.owner == user %}
								<form action="{% url 'vahay:delete_vahay' vahay.pk %}" method="POST">
									{% csrf_token %}
									<button type="submit" class="btn btn-xs btn-danger">Delete</button>
								</form>
							{% endif %}
						</div>
					</div>
					<div class="row">
						<div class="col-md-6">
							<p><span class="glyphicon glyphicon-globe" aria-hidden="true"></span>&nbsp;<strong>Address:</strong> {{ vahay.address }}</p>
						</div>
						<div class="col-md-2 col-md-offset-3">
								<a href="{% url 'vahay:reservations' vahay.pk %}" class="btn btn-xs btn-success">Reservations</a>
						</div>
					</div>
					<div class="row">
						<div class="col-md-6">
							<p><span class="glyphicon glyphicon-align-left" aria-hidden="true"></span>&nbsp;<strong>Other Details:</strong> <em>{{ vahay.description }}</em>
						</div>
					</div>
					<div class="row">	
						<div class="col-md-6">
							<p><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>&nbsp;<strong>Email:</strong> {{ vahay.email }}</p>
						</div>
					</div>
				</div>
				</div>
		  </div>
	</section>

	<section class="residents">
	  <div class="panel panel-default col-lg-6 col-lg-offset-3">
		<h3 style="text-align:center;">Residents</h3>
			<div class="panel-body">
				<div class="container-fluid">
					<ul class="list-group">
						{% for resident in residents %}
						  <li class="list-group-item" style="padding-bottom:15px;">{{ resident.name }} - {{ resident.age }} yr/s old
						  <a href="{% url 'vahay:delete_resident' resident.pk %}" style="float:right;" class="btn btn-sm btn-danger">delete</a>
						  <a href="{% url 'vahay:resident_profile' resident.pk %}" style="float:right;" class="btn btn-sm btn-success">view</a>
						  </li>
						{% endfor %}
					</ul>
				</div>
			</div>
		</div>
	</section>

{% endblock %}